Change dockerfile
LimeChain/as-substrate-runtime pull request #87
Opened 2020-10-13 08:30 UTC by dastanbeksamatov

Refactor dockerfile to accep `raw chain specs` as an argument

2020-10-13 11:33 UTC, Daniel-K-Ivanov requested changes

2020-10-13 11:33 UTC, Daniel-K-Ivanov commented on Dockerfile
> +ENTRYPOINT ["./node-template", "--rpc-methods=Unsafe", "--rpc-cors=all", "--rpc-external", "--execution", "Wasm", "--rpc-port", "9933", "--ws-port", "9944", "--port", "30333", "--name", "Node01", "--
`-chain` should not be populated. From the outside the command should something like:

```
docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 limechain/as-substrate:stable --chain=/customSpecRaw.json
```

2020-10-13 14:21 UTC, dastanbeksamatov commented on README.md
> +docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 -v "$(pwd)/customSpecRaw.json":/customSpecRaw.json limechain/as-substrate:stable --chain=./customSpecRaw.json
yeah. won't work without volumes, the entrypoint is executed inside the container and it doesn't have customSpecRaw.json file inside (afaik). Anyway, it throws `Error: Input("Error opening spec file: No such file or directory (os error 2)")` without volume

2020-10-14 06:26 UTC, Daniel-K-Ivanov commented on README.md
> +docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 -v "$(pwd)/customSpecRaw.json":/customSpecRaw.json limechain/as-substrate:stable --chain=./customSpecRaw.json
In this case, let's change the command to:
`docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 -v "{path-to-custom-spec-raw}/customSpecRaw.json":/customSpecRaw.json limechain/as-substrate:stable --chain=./customSpecRaw.json`

2020-10-15 06:55 UTC, Daniel-K-Ivanov requested changes

2020-10-15 06:55 UTC, Daniel-K-Ivanov commented on README.md
> +docker run -p 9933:9933 -p 9944:9944 -p 30333:30333 -v "{path-to-custom-spec-raw}/customSpecRaw.json":/customSpecRaw.json limechain/as-substrate:stable --chain=/customSpecRaw.json
I think that we do not need `--chain=/customSpecRaw.json` option

2020-10-15 06:55 UTC, Daniel-K-Ivanov commented on README.md
> +Assuming you have the generated raw chain specs file in the current directory, run the executable:
Actually, now we do not have to assume that the raw chain spec file is created in the current directory. In the example below there is {path-to-custom-spec-raw}

2020-10-15 06:55 UTC, Daniel-K-Ivanov commented on README.md
> +NOTE: Make sure the path to `customSpecRaw.json` is absolute, otherwise Docker will throw an error.
The mapping to the inner data in the container must be absolute, but not the outer part: "{path-to-custom-spec-raw}/customSpecRaw.json"

2020-10-15 06:55 UTC, Daniel-K-Ivanov commented on Dockerfile
> +ENTRYPOINT ["./node-template", "--rpc-methods=Unsafe", "--rpc-cors=all", "--rpc-external", "--execution", "Wasm", "--rpc-port", "9933", "--ws-port", "9944", "--port", "30333", "--name", "Node01", "--
It is purpose defying to have Dockerfile building the node when we are pulling it from an image `limechain/as-substrate-node` and just exposing the ports + defining the arguments. Why are we not using only the `as-substrate-node` image and just provide the custom spec raw. We do not actually need 2 images. 
Let's discuss it

2020-10-16 06:21 UTC, Daniel-K-Ivanov approved these changes

2020-10-16 06:21 UTC, merged